### ISSUE TITLE
PICOS and some sympy functions are not compatible

### ISSUE THREAD

**Issue by hsteinshiromoto** [gsagnol/picos#46]
I have found an issue while defining the computing the Jacobian of a variable using PICOS and sympy (Python). Consider the following MWE:

```
import picos as pic
import sympy as sp
Pr = pic.Problem()

x = Pr.add_variable("x", 1)

F = sp.Matrix([x**5, 1])
print F.jacobian(x)
```

When I execute it, I get the following message:

```
Traceback (most recent call last):
  File "C:/***/test.py", line 9, in <module>
    F = sp.Matrix([x**5, 1])
  File "C:\***\Anaconda2\lib\site-packages\sympy\matrices\dense.py", line 611, in __new__
    return cls._new(*args, **kwargs)
  File "C:\***\Anaconda2\lib\site-packages\sympy\matrices\dense.py", line 603, in _new
    rows, cols, flat_list = cls._handle_creation_inputs(*args, **kwargs)
  File "C:\***\Anaconda2\lib\site-packages\sympy\matrices\matrices.py", line 191, in _handle_creation_inputs
    flat_list = [cls._sympify(i) for i in in_mat]
  File "C:\***\Anaconda2\lib\site-packages\sympy\core\sympify.py", line 324, in sympify
    raise SympifyError('could not parse %r' % a, exc)
sympy.core.sympify.SympifyError: Sympify of expression 'could not parse u'# pth power expression: ( x)**5 #'' failed, because of exception being raised:
SyntaxError: unexpected EOF while parsing (<string>, line 1)
```

Since I need to compute the Jacobian to use in a convex optimisation problem. Does someone know how I can take derivatives with PICOS?

Thanks in advance,

**Comment by gsagnol** [comment]
simpy and picos are not compatible. However, I think it should be easy to make a function that casts a simpy variable into a picos variable. Tell me if this is what you need.
